---
title: "raw data"
author: "Lessly Ortiz, Elysia Pil, Sophia Silovsky"
format: pdf
---

```{r}
qplot(x=interaction(busy, company), y=sit_and_eat, data=df_dropped, xlab = "Interaction between Busyness and Company", ylab="Agreement Level", main = "Distribution of Agreement Level across Groups",geom="boxplot") + theme(axis.title = element_text(size = 15))

sit_eat_sd <- df_dropped|>
  group_by(interaction(busy, company)) |>
  summarise(Group_mean=mean(sit_and_eat), Sample_size=n(), standard_dev=sd(sit_and_eat))

TukeyNonaddPlot(sit_and_eat~busy*company, data=df_dropped)

with(df_dropped,interaction.plot(busy, company, sit_and_eat))

dining_aov <- aov(sit_and_eat~busy*company, data=df_dropped)

summary(dining_aov)

# effect of going from an empty dining hall to a busy dining hall
effect_size = (1.3125000 / sqrt(1.813))
# 0.97, based on Cohen's effect size, there is a large effect 

TukeyHSD(dining_aov)
ci <- TukeyHSD(dining_aov)
plot(ci)
plot(dining_aov, which=2)
bonfCI(df$sit_and_eat, interaction(df$busy, df$company), conf.level = 0.95)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rio)
library(asbio)
library(stringr)
library(Stat2Data)
library(car)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
data <- read.csv('Mini-project+2_May+5,+2023_13.13.csv')

# clean_df <- subset(data, select = c(ResponseId,Finished,Q1, Q2, Q2.1,Q4, Q5, Q16_1, Q16_2,Q16_3,Q16_4,Treatment_DO))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
df <- data |> 
  select(c(7, 18:27))|>
  filter(Finished == "True") |>
  filter(!row_number() %in% c(1,2))|>
  rename("consent"="Q1", 
         "dietary_resitriction"="Q2", 
         "class" ="Q2.1", 
         "gender"="Q4", 
         "neighborhood"="Q5", 
         "sit_and_eat"="Q16_1", 
         "find_new_dining"="Q16_2", 
         "grab_and_go"="Q16_3","enjoy_eating"="Q16_4", 
         "treatment"="Treatment_DO")|>
  
  mutate(treatment = str_replace(treatment, "Q7", "lamont_alone_busy")) |>
  mutate(treatment = str_replace(treatment, "Q8", "lamont_friends_busy")) |>
  mutate(treatment = str_replace(treatment, "Q9", "nogi_alone_normal")) |>
  mutate(treatment = str_replace(treatment, "Q10", "nogi_friends_normal")) |>
  mutate(treatment = str_replace(treatment, "Q11", "cz_alone_empty")) |>
  mutate(treatment = str_replace(treatment, "Q12", "cz_friends_empty"))|>
  
  #response variable transformation into numeric values with strongly disagree=1 and strongly agree=7
  mutate(sit_and_eat = str_replace(sit_and_eat, "Strongly disagree", "1"))|>
  mutate(sit_and_eat = str_replace(sit_and_eat, "Strongly agree", "7"))|>
  mutate(sit_and_eat = str_replace(sit_and_eat, "Somewhat disagree", "2"))|>  
  mutate(sit_and_eat = str_replace(sit_and_eat, "Somewhat agree", "6"))|>  
  mutate(sit_and_eat = str_replace(sit_and_eat, "Disagree", "3"))|>  
  mutate(sit_and_eat = str_replace(sit_and_eat, "Agree", "5"))|>  
  mutate(sit_and_eat = str_replace(sit_and_eat, "Neither agree nor disagree", "4"))|>
  
  mutate(find_new_dining = str_replace(find_new_dining, "Strongly disagree", "1"))|>
  mutate(find_new_dining = str_replace(find_new_dining, "Strongly agree", "7"))|>
  mutate(find_new_dining = str_replace(find_new_dining, "Somewhat disagree", "2"))|>  
  mutate(find_new_dining = str_replace(find_new_dining, "Somewhat agree", "6"))|>  
  mutate(find_new_dining = str_replace(find_new_dining, "Disagree", "3"))|>  
  mutate(find_new_dining = str_replace(find_new_dining, "Agree", "5"))|>  
  mutate(find_new_dining = str_replace(find_new_dining, "Neither agree nor disagree", "4"))|>
  
  mutate(grab_and_go = str_replace(grab_and_go, "Strongly disagree", "1"))|>
  mutate(grab_and_go = str_replace(grab_and_go, "Strongly agree", "7"))|>
  mutate(grab_and_go = str_replace(grab_and_go, "Somewhat disagree", "2"))|>  
  mutate(grab_and_go = str_replace(grab_and_go, "Somewhat agree", "6"))|>  
  mutate(grab_and_go = str_replace(grab_and_go, "Disagree", "3"))|>  
  mutate(grab_and_go = str_replace(grab_and_go, "Agree", "5"))|>  
  mutate(grab_and_go = str_replace(grab_and_go, "Neither agree nor disagree", "4"))|>
  
  mutate(enjoy_eating = str_replace(enjoy_eating, "Strongly disagree", "1"))|>
  mutate(enjoy_eating = str_replace(enjoy_eating, "Strongly agree", "7"))|>
  mutate(enjoy_eating = str_replace(enjoy_eating, "Somewhat disagree", "2"))|>  
  mutate(enjoy_eating = str_replace(enjoy_eating, "Somewhat agree", "6"))|>  
  mutate(enjoy_eating = str_replace(enjoy_eating, "Disagree", "3"))|>  
  mutate(enjoy_eating = str_replace(enjoy_eating, "Agree", "5"))|>  
  mutate(enjoy_eating = str_replace(enjoy_eating, "Neither agree nor disagree", "4"))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

df$sit_and_eat <-as.numeric(df$sit_and_eat)
df$find_new_dining <-as.numeric(df$find_new_dining)
df$grab_and_go <-as.numeric(df$grab_and_go)
df$enjoy_eating <-as.numeric(df$enjoy_eating)


#drop_na("treatment", "intelligent_life", "Major")|> ???what do with na's???  



```


```{r echo=FALSE, message=FALSE, warning=FALSE}

#interaction group

df$group[df$treatment == "nogi_alone_normal"] <- 1
df$group[df$treatment == "nogi_friends_normal"] <- 2

df$group[df$treatment == "lamont_alone_busy"] <- 3
df$group[df$treatment == "lamont_friends_busy"] <- 4

df$group[df$treatment == "cz_alone_empty"] <- 5
df$group[df$treatment == "cz_friends_empty"] <- 6


#with friends or not

df$company[df$treatment == "nogi_alone_normal"] <- "Alone"
df$company[df$treatment == "nogi_friends_normal"] <- "Friends"

df$company[df$treatment == "lamont_alone_busy"] <- "Alone"
df$company[df$treatment == "lamont_friends_busy"] <- "Friends"

df$company[df$treatment == "cz_alone_empty"] <- "Alone"
df$company[df$treatment == "cz_friends_empty"] <- "Friends"


#Bussiness

df$busy[df$treatment == "nogi_alone_normal"] <- "Normal"
df$busy[df$treatment == "nogi_friends_normal"] <- "Normal"

df$busy[df$treatment == "lamont_alone_busy"] <- "Busy"
df$busy[df$treatment == "lamont_friends_busy"] <- "Busy"

df$busy[df$treatment == "cz_alone_empty"] <- "Empty"
df$busy[df$treatment == "cz_friends_empty"] <- "Empty"


df$busy <- as.factor(df$busy)
df$company <- as.factor(df$company)
df$group <- as.factor(df$group)
```

```{r}
export(df, "df.csv")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
#Data Exploration

df_dropped <- df |> 
  drop_na()

summary(df)

ggplot(data = df_dropped, mapping = aes(x=group, y =sit_and_eat,  fill = group)) +
geom_col()+
  labs(title = "Group Agreement to Sit and Eat",
       y = "Total Level of Agreement(1:Strongly Disagree, 7:Strongly Agree)", fill = "Treatment Group",
       x = "Treatment Group")

ggplot(data = df_dropped, mapping = aes(x=group, y =find_new_dining,  fill = group)) +
geom_col()+
  labs(title = "Group Agreement to Find new Dining Hall",
       y = "Total Level of Agreement(1:Strongly Disagree, 7:Strongly Agree)", fill = "Treatment Group",
       x = "Treatment Group")

ggplot(data = df_dropped, mapping = aes(x=group, y =enjoy_eating,  fill = group)) +
geom_col()+
  labs(title = "Group Agreement to Enjoy Eating",
       y = "Total Level of Agreement(1:Strongly Disagree, 7:Strongly Agree)", fill = "Treatment Group",
       x = "Treatment Group")



qplot(x=group, y=sit_and_eat, data=df_dropped, ylab="Agreement Level", geom="boxplot") +theme(axis.title = element_text(size = 15))
qplot(x=group, y=find_new_dining, data=df_dropped, ylab="Agreement Level", geom="boxplot") +theme(axis.title = element_text(size = 15))
qplot(x=group, y=grab_and_go, data=df_dropped, ylab="Agreement Level", geom="boxplot") +theme(axis.title = element_text(size = 15))
qplot(x=group, y=enjoy_eating, data=df_dropped, ylab="Agreement Level", geom="boxplot") +theme(axis.title = element_text(size = 15))

qplot(x=interaction(busy, company), y=sit_and_eat, data=df_dropped, ylab="Agreement Level", geom="boxplot") +theme(axis.title = element_text(size = 15))

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

sit_eat_sd <- df_dropped|>
  group_by(interaction(busy, company)) |>
  summarise(Group_mean=mean(sit_and_eat), Sample_size=n(), standard_dev=sd(sit_and_eat))

find_new_sd <- df_dropped|>
  group_by(group) |>
  summarise(Group_mean=mean(find_new_dining), Sample_size=n(), standard_dev=sd(find_new_dining))

grab_sd <- df_dropped|> 
  group_by(group) |>
  summarise(Group_mean=mean(grab_and_go), Sample_size=n(), standard_dev=sd(grab_and_go))

enjoy_sd <- df_dropped|> 
  group_by(group) |>
  summarise(Group_mean=mean(enjoy_eating), Sample_size=n(), standard_dev=sd(enjoy_eating))

export(df_dropped, "df_dropped.csv")
```



interaction

```{r echo=FALSE, message=FALSE, warning=FALSE}

ggplot(df_dropped, aes(x=interaction(var1, var2), y=sit_and_eat))+
  geom_boxplot()


with(df_dropped,interaction.plot(busy, company, sit_and_eat))

with(df_dropped,interaction.plot(var1, var2, enjoy_eating))

with(df_dropped,interaction.plot(var1, var2, grab_and_go))

with(df_dropped,interaction.plot(var1, var2, find_new_dining))


dining_aov <- aov(sit_and_eat~busy*company, data=df_dropped)

summary(dining_aov)


dining_aov2 <- aov(enjoy_eating~var1*var2, data=df_dropped)

summary(dining_aov2)

dining_aov3 <- aov(find_new_dining~var1*var2, data=df_dropped)

summary(dining_aov3)

dining_aov4 <- aov(grab_and_go~var1*var2, data=df_dropped)

summary(dining_aov4)

```


```{r}
TukeyHSD(dining_aov)
plot(dining_aov, which=2)
bonfCI(df$sit_and_eat, interaction(df$busy, df$company), conf.level = 0.95)

TukeyHSD(dining_aov2)
plot(dining_aov2, which=2)
bonfCI(df$enjoy_eating, interaction(df$var1, df$var2), conf.level = 0.95)

TukeyHSD(dining_aov3)
plot(dining_aov3, which=2)

TukeyHSD(dining_aov4)
plot(dining_aov4, which=2)
```


```{r}
TukeyNonaddPlot(sit_and_eat~busy*company, data=df_dropped)
leveneTest(sit_and_eat~var1*var2, data=df_dropped)

TukeyNonaddPlot(enjoy_eating~var1*var2, data=df_dropped)
leveneTest(enjoy_eating~var1*var2, data=df_dropped)

TukeyNonaddPlot(grab_and_go~var1*var2, data=df_dropped)


TukeyNonaddPlot(find_new_dining~var1*var2, data=df_dropped)
```

```{r}
cellmeans2 <- df_dropped |>
  group_by(var1, var2)|>
  summarise(mean=log(mean(enjoy_eating)), sd=sd(enjoy_eating))


ggplot(cellmeans2, aes(x=mean, y=sd)) + geom_point() 

summary(lm(sd~mean, data=cellmeans2))
```

```{r}
#non-parametric tests



kruskal.test(sit_and_eat~var1, data=df_dropped)
kruskal.test(sit_and_eat~var2, data=df_dropped)#sigfig

kruskal.test(enjoy_eating~var1, data=df_dropped)
kruskal.test(enjoy_eating~var2, data=df_dropped)

kruskal.test(find_new_dining~var1, data=df_dropped)
kruskal.test(find_new_dining~var2, data=df_dropped)#sigfig


kruskal.test(grab_and_go~var1, data=df_dropped)
kruskal.test(grab_and_go~var2, data=df_dropped)#sigfig

```


```{r}
logdata <- df_dropped |>
  group_by(var1, var2)|>
  summarise(mean=log(mean(sit_and_eat)), sd=sd(sit_and_eat))


ggplot(logdata, aes(x=mean, y=sd)) + geom_point() 

summary(lm(sd~mean, data=logdata))
```
```{r}
ggplot(sit_eat_sd, aes(x = log(Group_mean), y = log(standard_dev))) + geom_point()

summary(lm(log(standard_dev)~log(Group_mean), data = enjoy_sd))
```
```{r}
ggplot(sit_eat_sd, aes(x = log(Group_mean), y = log(standard_dev))) + geom_point()

summary(lm(log(standard_dev)~log(Group_mean), data = sit_eat_sd))
```

```{r}
ggplot(find_new_sd, aes(x = log(Group_mean), y = log(standard_dev))) + geom_point()

summary(lm(log(standard_dev)~log(Group_mean), data = find_new_sd))
```

```{r}
ggplot(grab_sd, aes(x = log(Group_mean), y = log(standard_dev))) + geom_point()

summary(lm(log(standard_dev)~log(Group_mean), data = grab_sd))
```